# Generated by Django 3.1.7 on 2021-05-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='material_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='materials',
            old_name='material_name',
            new_name='name',
        ),
    ]
