# Generated by Django 3.1.7 on 2021-05-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20210523_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
