# Generated by Django 3.2.3 on 2021-06-02 12:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materials_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
