# Generated by Django 4.1.2 on 2022-10-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pdv",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_pdv", models.IntegerField(default=0, max_length=3)),
                ("balance_pdv", models.FloatField(default=0, max_length=10)),
                ("active_pdv", models.IntegerField(default=0, max_length=1)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
