# Generated by Django 4.1.2 on 2022-10-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0002_pdv_user_pdv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdv",
            old_name="user_pdv",
            new_name="id_user_pdv",
        ),
    ]
