# Generated by Django 4.1.2 on 2022-10-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0002_alter_pdv_id_pdv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdv",
            name="active_pdv",
            field=models.BooleanField(default=1),
        ),
    ]
