# Generated by Django 4.1.2 on 2022-10-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0003_rename_user_pdv_pdv_id_user_pdv"),
    ]

    operations = [
        migrations.CreateModel(
            name="forma_pgto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_pgto", models.CharField(max_length=200)),
            ],
        ),
    ]
