# Generated by Django 4.1.2 on 2022-10-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0004_forma_pgto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forma_pgto",
            old_name="tipo_pgto",
            new_name="payment_type",
        ),
        migrations.RemoveField(
            model_name="pdv",
            name="id",
        ),
        migrations.AlterField(
            model_name="pdv",
            name="code_pdv",
            field=models.IntegerField(
                default=0, max_length=3, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="cupom",
            fields=[
                (
                    "codigo_cupom",
                    models.CharField(
                        max_length=7, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("acrescimo", models.DecimalField(decimal_places=2, max_digits=9)),
                ("dt_cupom", models.DateTimeField()),
                ("preco_custo", models.DecimalField(decimal_places=2, max_digits=9)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=9)),
                ("cancela_cupom", models.BooleanField(default=False)),
                ("desconto", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "code_pdv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pdv.pdv"
                    ),
                ),
                (
                    "codigo_pgto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pdv.forma_pgto"
                    ),
                ),
            ],
        ),
    ]
