# Generated by Django 4.1.2 on 2022-10-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0004_remove_pdv_code_pdv_alter_pdv_balance_pdv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cupom",
            name="codigo_cupom",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
