# Generated by Django 4.1.2 on 2022-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0005_alter_cupom_codigo_cupom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cupom",
            name="acrescimo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="cupom",
            name="desconto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="cupom",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="cupom",
            name="preco_custo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
