# Generated by Django 4.1.2 on 2022-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0005_rename_tipo_pgto_forma_pgto_payment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdv",
            name="active_pdv",
            field=models.BooleanField(default=0),
        ),
    ]
