# Generated by Django 4.1.2 on 2022-10-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_products_id_alter_products_active_and_more"),
        ("pdv", "0006_alter_pdv_active_pdv"),
    ]

    operations = [
        migrations.CreateModel(
            name="item_cupom",
            fields=[
                (
                    "codigo_item",
                    models.CharField(
                        max_length=7, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("preco", models.DecimalField(decimal_places=2, max_digits=9)),
                ("limite_cliente", models.IntegerField(default=0, max_length=3)),
                ("qtd_item", models.FloatField(default=0, max_length=5)),
                (
                    "codigo_cupom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pdv.cupom"
                    ),
                ),
                (
                    "codigo_int",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
        ),
    ]
