# Generated by Django 4.1.2 on 2022-11-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0006_alter_cupom_acrescimo_alter_cupom_desconto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item_cupom",
            name="description",
            field=models.CharField(default="", max_length=200),
        ),
    ]
