# Generated by Django 4.1.2 on 2022-11-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0007_item_cupom_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item_cupom",
            name="codigo_item",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
