# Generated by Django 4.1.2 on 2022-10-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0007_item_cupom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item_cupom",
            name="limite_cliente",
            field=models.IntegerField(default=0, max_length=3, null=True),
        ),
    ]
