# Generated by Django 4.1.2 on 2022-10-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0008_alter_item_cupom_limite_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item_cupom",
            name="limite_cliente",
            field=models.IntegerField(null=True),
        ),
    ]
