# Generated by Django 4.1.2 on 2022-11-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0008_alter_item_cupom_codigo_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item_cupom",
            name="qtd_item",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
