# Generated by Django 4.1.2 on 2022-10-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0009_alter_item_cupom_limite_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="cupom",
            name="fecha_cupom",
            field=models.BooleanField(default=0),
        ),
    ]
