# Generated by Django 4.1.2 on 2022-11-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0009_alter_item_cupom_qtd_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item_cupom",
            name="qtd_item",
            field=models.IntegerField(default=0),
        ),
    ]
