# Generated by Django 4.1.2 on 2022-10-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(default="", max_length=200)),
                ("active", models.IntegerField(default=0, max_length=1)),
                ("sale_price", models.FloatField(default=0, max_length=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("dt_last_sale", models.DateTimeField(auto_now=True)),
                ("markup_sale", models.FloatField(default=0, max_length=5)),
                ("price_cost", models.FloatField(default=0, max_length=10)),
                ("stock", models.FloatField(default=0, max_length=5)),
                ("stock_min", models.FloatField(default=0, max_length=5)),
                ("code_int", models.IntegerField(default=0, max_length=7)),
                ("code_ean", models.CharField(max_length=14, unique=True)),
            ],
        ),
    ]
