# Generated by Django 4.1.2 on 2022-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="price_cost",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name="products",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
