# Generated by Django 4.1.2 on 2022-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_products_price_cost_alter_products_sale_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="id",
        ),
        migrations.AlterField(
            model_name="products",
            name="active",
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name="products",
            name="code_int",
            field=models.IntegerField(
                default=0, max_length=7, primary_key=True, serialize=False
            ),
        ),
    ]
